export const SET_POSITIONS_TO_CATEGORY = 'SET_POSITIONS_TO_CATEGORY';
export const GET_MENU = 'GET_MENU';
export const ADD_POSITION_STRING_TO_ORDER = 'ADD_POSITION_STRING_TO_ORDER';
export const CALCULATE_SUMMARY_OF_CURRENT_ORDER = 'CALCULATE_SUMMARY_OF_CURRENT_ORDER';
export const CALCULATE_ORDER_SUMMARY = 'CALCULATE_ORDER_SUMMARY';
export const ADD_POSITION_TO_ORDER = 'ADD_POSITION_TO_ORDER';
export const REMOVE_POSITION_FROM_ORDER = 'REMOVE_POSITION_FROM_ORDER';
export const REMOVE_POSITION_STRING_FROM_ORDER = 'REMOVE_POSITION_STRING_FROM_ORDER';

