export const GET_MENU = 'GET_MENU';
export const CALCULATE_ORDER_SUMMARY = 'CALCULATE_ORDER_SUMMARY';
export const ADD_POSITION_TO_ORDER = 'ADD_POSITION_TO_ORDER';
export const REMOVE_POSITION_FROM_ORDER = 'REMOVE_POSITION_FROM_ORDER';
export const REMOVE_POSITION_STRING_FROM_ORDER = 'REMOVE_POSITION_STRING_FROM_ORDER';
export const LOAD_ORDER_FROM_GUEST_TABLET = 'LOAD_ORDER_FROM_GUEST_TABLET';
export const LOAD_GUEST_TABLETS = 'LOAD_GUEST_TABLETS';
export const LOAD_POSITIONS_MODS = 'LOAD_POSITIONS_MODS';
export const LOAD_COMMON_MODS = 'LOAD_COMMON_MODS';

